version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: ./api_yamdb/.env
  web:
    build: .
    restart: always
    expose:
      - 8000
    depends_on:
      - db
    env_file: ./api_yamdb/.env
    command: bash -c "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py loaddata fixture.json && gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/app/web/static
  nginx:
    build: ./nginx
    volumes:
    - static_volume:/static
    ports:
    - 8000:80
    depends_on:
      - web


volumes:
  postgres_data:
  static_volume:
